# Generated by Django 5.1.3 on 2024-11-14 12:00

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerriderequest',
            name='dropoff_latitude',
        ),
        migrations.RemoveField(
            model_name='passengerriderequest',
            name='dropoff_longitude',
        ),
        migrations.RemoveField(
            model_name='passengerriderequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='passengerriderequest',
            name='pickup_latitude',
        ),
        migrations.RemoveField(
            model_name='passengerriderequest',
            name='pickup_longitude',
        ),
        migrations.RemoveField(
            model_name='ridedetails',
            name='end_latitude',
        ),
        migrations.RemoveField(
            model_name='ridedetails',
            name='end_longitude',
        ),
        migrations.RemoveField(
            model_name='ridedetails',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ridedetails',
            name='start_latitude',
        ),
        migrations.RemoveField(
            model_name='ridedetails',
            name='start_longitude',
        ),
        migrations.AddField(
            model_name='passengerriderequest',
            name='dropoff_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='passengerriderequest',
            name='pickup_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='ridedetails',
            name='end_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='ridedetails',
            name='route_line',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='ridedetails',
            name='start_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='ridedetails',
            name='available_seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='ridedetails',
            name='end_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ridedetails',
            name='start_location',
            field=models.CharField(max_length=255),
        ),
    ]
