# Generated by Django 5.1.3 on 2024-11-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerriderequest',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
