# Generated by Django 5.1.3 on 2024-11-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_passengerriderequest_payment_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ridedetails',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ride Detail', 'verbose_name_plural': 'Ride Details'},
        ),
        migrations.AlterField(
            model_name='passengerriderequest',
            name='payment_completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
