# Generated by Django 5.1.3 on 2024-11-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
