# Generated by Django 5.1.2 on 2024-11-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PASSWORD_RESET', 'password_reset'), ('PHONE', 'Phone')], default='EMAIL', max_length=20),
        ),
    ]
