# Generated by Django 5.1.3 on 2024-11-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_total_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_passengers',
        ),
    ]
