# Generated by Django 5.1.3 on 2024-11-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_vehicle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vehicle_name',
        ),
    ]
