# Generated by Django 5.1.2 on 2024-10-29 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otp',
            name='authenticat_user_id_0e199c_idx',
        ),
    ]
